spring.application.name=central-portal
spring.datasource.url=jdbc:mysql://localhost:3306/university_db
#Username และ Password ของ MySQL
spring.datasource.username=root
spring.datasource.password=12345678

#Hibernate สร้างตารางให้เราอัตโนมัติ
spring.jpa.hibernate.ddl-auto=create

# 🎯 2 บรรทัดที่เพิ่มเข้ามาสำหรับระบบข้อมูลจำลอง (data.sql)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#แสดงคำสั่ง SQL ใน Terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=GMAIL_HERE
spring.mail.password=APP_PASSWORD_HERE
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# TU API Configuration
tu.api.url=https://restapi.tu.ac.th/api/v1/auth/Ad/login
tu.api.key=dummy_key_1234